name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-environment:
    name: Set up Python 3.11.4 Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11.4
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

  run-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11.4
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          source venv/bin/activate
          python3 -m unittest unit_tests.py -v

  lint-check:
    name: Lint Check
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11.4
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Linter
        run: |
          source venv/bin/activate
          pylint **/*.py

  security-check:
    name: Security Check
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11.4
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bandit Security Scan
        run: |
          source venv/bin/activate
          bandit -r ./

  build:
    name: Build the Application
    runs-on: ubuntu-latest
    needs: 
      - run-tests
      - lint-check
      - security-check
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11.4
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build the Application
        run: |
          source venv/bin/activate
          pyinstaller --onefile main.py
